channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.0
  - jupyterlab=1.2.10
  - jupyter-rsession-proxy
  - jupyter-server-proxy
  - jupyterlab_server=1.1.1
  - widgetsnbextension=3.5.1
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - ipykernel=5.2.0
  - r-irkernel
  - r-tidyverse
  - r-seurat
  - r-knitr
  - r-kableextra
  - r-ggplot2
  - r-dplyr
  - r-wgcna
  - r-cowplot
  - r-rstudioapi
  - bioconductor-limma
  - bioconductor-savr
  - bioconductor-topgo
  - bioconductor-monocle
  - pip
  - pip:
    - cellphonedb
