channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - r-base=4.0
  - r-irkernel
  - jupyter-server-proxy
  - r-tidyverse
  - r-seurat
  - r-knitr
  - r-kableextra
  - r-ggplot2
  - r-dplyr
  - r-wgcna
  - r-cowplot
  - r-rstudioapi
  - bioconductor-limma
  - bioconductor-savr
  - bioconductor-topgo
  - bioconductor-monocle
  - rstudio
  - pip
  - pip:
    - cellphonedb
