#!/bin/bash

set -e

jupyter labextension install @jupyterlab/server-proxy --no-build && \
jupyter lab build --dev-build=False && \
npm cache clean --force && \
rm -rf $CONDA_DIR/share/jupyter/lab/staging && \
rm -rf /home/$NB_USER/.cache/yarn && \
rm -rf /home/$NB_USER/.node-gyp

sudo apt-get update && \
curl --silent -L --fail https://download2.rstudio.org/rstudio-server-1.1.419-amd64.deb > /tmp/rstudio.deb && \
sudo echo '24cd11f0405d8372b4168fc9956e0386 /tmp/rstudio.deb' | md5sum -c - && \
sudo apt-get install -y /tmp/rstudio.deb && \
sudo rm /tmp/rstudio.deb && \
sudo apt-get clean

export PATH=$PATH:/usr/lib/rstudio-server/bin
